import React, { useState } from "react";
import { Formfeild, Loader } from "../Components";
import { useNavigate } from "react-router-dom";
import { preview } from "../assets";
import { GetRandomPrompt } from "../Utils";

const CreatePost = () => {
  const [loading, setloading] = useState(false);
  const Navigate = useNavigate();
  const [Form, setForm] = useState({
    name: "",
    prompt: "",
    picture: "",
  });
  const [GeneratingImg, setGeneratingImg] = useState(false);
  const GenerateIMG = async () => {
    if (Form.prompt) {
      try {
        setGeneratingImg(true);
        const response = await fetch("http://localhost:8080/api/v1/AiIMAGE", {
          method: "POST",
          headers: {
            "Content-Type": "application/json",
          },
          body: JSON.stringify({
            prompt: Form.prompt,
          }),
        });

        const data = await response.json();
        setForm({ ...Form, picture: `data:image/jpeg;base64,${data.photo}` });
      } catch (err) {
        alert(err);
      } finally {
        setGeneratingImg(false);
      }
    } else {
      alert("Please provide proper prompt");
    }
  };
  const handlesubmit = async (e) => {
    e.preventDefault();
    if (Form.prompt && Form.picture) {
      setloading(true);
      console.log("running");
      try {
        const Response = await fetch("http://localhost:8080/api/v1/post", {
          method: "POST",
          headers: {
            "Content-Type": "application/json",
          },
          body: JSON.stringify({ ...Form }),
        });
        await Response.json();
        console.log(Response);
        Navigate("/");
      } catch (error) {
        console.log(error);
      } finally {
        setloading(false);
      }
    } else {
      alert("Please Enter Prompt and Generate The Image");
    }
  };
  const handleChange = (e) => {
    setForm({ ...Form, [e.target.name]: e.target.value });
  };
  const handleIsSupriseME = () => {
    const Suprise = GetRandomPrompt();
    setForm({ ...Form, prompt: Suprise });
  };
  return (
    <div className="min-h-screen flex items-center justify-center px-4 sm:px-6 lg:px-8 py-12">
      <div className="w-full max-w-5xl">
        {/* Header Section */}
        <div className="text-center mb-12">
          <h1 className="font-extrabold text-4xl sm:text-5xl md:text-6xl bg-gradient-to-r from-blue-400 via-purple-400 to-pink-400 bg-clip-text text-transparent mb-4">
            Create
          </h1>
          <p className="text-lg sm:text-xl text-gray-300">
            Create Visually Stunning AI Images Generated By GenZAI
          </p>
        </div>

        {/* Main Form Container */}
        <form className="w-full" onSubmit={handlesubmit}>
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-8 lg:gap-12">
            {/* Left Section - Form Fields */}
            <div className="space-y-6">
              {/* Name Field */}
              <div>
                <label className="block text-sm font-medium text-gray-300 mb-3">
                  Your Name
                </label>
                <Formfeild
                  name="name"
                  type="text"
                  placeholder="Enter Your Name"
                  handleChange={handleChange}
                  value={Form.name}
                />
              </div>

              {/* Prompt Field */}
              <div>
                <div className="flex items-center justify-between mb-3">
                  <label className="block text-sm font-medium text-gray-300">
                    Prompt
                  </label>
                  <button
                    type="button"
                    onClick={handleIsSupriseME}
                    className="px-3 py-1 text-xs font-semibold text-gray-900 bg-white hover:bg-gray-100 rounded transition-all duration-300"
                  >
                    Surprise Me
                  </button>
                </div>
                <Formfeild
                  name="prompt"
                  type="text"
                  placeholder="A comic book cover of a superhero wearing headphones"
                  handleChange={handleChange}
                  value={Form.prompt}
                />
              </div>

              {/* Generate Button */}
              <button
                className="w-full px-6 py-3 rounded-lg font-semibold text-white bg-gradient-to-r from-blue-600 to-purple-600 hover:from-blue-700 hover:to-purple-700 transition-all duration-300 shadow-lg hover:shadow-purple-500/50 text-base"
                type="button"
                onClick={GenerateIMG}
              >
                {GeneratingImg ? (
                  <span className="flex items-center justify-center gap-2">
                    <span className="inline-block animate-spin">⚙️</span>
                    Generating...
                  </span>
                ) : (
                  "Generate Image"
                )}
              </button>
            </div>

            {/* Right Section - Preview */}
            <div className="flex flex-col items-center justify-center">
              <div className="relative w-full aspect-square max-w-xs sm:max-w-sm md:max-w-md bg-white rounded-2xl border-2 border-purple-500/30 shadow-2xl overflow-hidden hover:shadow-purple-500/20 transition-all duration-300">
                {Form.picture ? (
                  <img
                    className="w-full h-full object-contain p-4"
                    src={Form.picture}
                    alt={Form.prompt}
                  />
                ) : (
                  <div className="w-full h-full flex items-center justify-center bg-gray-100">
                    <img
                      className="w-1/2 h-1/2 object-contain opacity-50"
                      src={preview}
                      alt="preview"
                    />
                  </div>
                )}
                {GeneratingImg && (
                  <div className="absolute inset-0 flex justify-center items-center bg-black/60 backdrop-blur-sm rounded-2xl">
                    <Loader />
                  </div>
                )}
              </div>
            </div>
          </div>

          {/* Share Section */}
          <div className="mt-16 text-center">
            <div className="mb-6">
              <p className="text-gray-300 text-base sm:text-lg leading-relaxed">
                Once Created Your Amazing Design, You Can Share It With Our
                Community For Free
              </p>
            </div>
            <button
              type="submit"
              className="inline-block px-8 py-3 rounded-lg font-semibold text-white bg-gradient-to-r from-purple-600 to-blue-600 hover:from-purple-700 hover:to-blue-700 transition-all duration-300 shadow-lg hover:shadow-blue-500/50 text-base"
            >
              {loading ? (
                <span className="flex items-center justify-center gap-2">
                  <span className="inline-block animate-spin">⚙️</span>
                  Sharing...
                </span>
              ) : (
                "Share It With Community"
              )}
            </button>
          </div>
        </form>
      </div>
    </div>
  );
};

export default CreatePost;
